workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'

variables:
  GRADLE_USER_HOME: "/home/gitlab-runner/.gradle"

cache:
  key:
    files: [frontend/pnpm-lock.yaml]
  paths: [.pnpm-store, .gradle]
  policy: pull-push

build-deploy:
  stage: deploy
  tags: [deploy]
  script:
    # Compile
    - cd backend && ./gradlew :blog-app:bootJar
    - sudo cp blog-app/build/libs/backend.jar /opt/arorms/blog/backend.jar
    - cd ..

    - cd frontend && pnpm install && pnpm --filter @blog/public build
    - sudo rsync -az --delete apps/public/dist/ /var/www/arorms/blog/
    - cd ..

    # Install service and nginx conf
    - sudo cp etc/blog-nginx-public.conf /etc/nginx/sites-available/blog.conf
    - sudo cp etc/blog-spring.service /etc/systemd/system/blog-spring.service
    - sudo systemctl daemon-reload
#    - cp etc/blog-spring.env

    # Restart service and nginx
    - sudo systemctl restart blog-spring.service
    - sudo systemctl reload nginx