### Get Picture
GET {{baseUrl}}/uploads/22982f45-2527-425a-9808-7feae0e10f2b.JPG

### GET Picture thumbnail
GET {{baseUrl}}/uploads/thumbnails/thumb_22982f45-2527-425a-9808-7feae0e10f2b.JPG

### GET Picture file by api
GET {{baseUrl}}/api/pictures/files/a5bb7b95-3056-4f7e-9791-aa0ac2a2d8f9.JPG