### Upload Picture
POST http://localhost:8080/api/pictures/upload
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="CZ2025.JPG"
Content-Type: image/jpeg

< C:\Development\CZ2025.JPG
--boundary
Content-Disposition: form-data; name="uploaderId"

1
--boundary
Content-Disposition: form-data; name="alt"

--boundary--
